# This file was generated by GoReleaser. DO NOT EDIT.
class GolangRepoTemplate < Formula
  desc "golang-repo-template"
  homepage "https://ultre.me""
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ultreme/golang-repo-template/releases/download/v1.0.0/golang-repo-template_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "9c630804b9b8e9eafedf1fefaa6916ef952161b2be8e5af5f85e14b40e7d10a7"
  elsif OS.linux?
    url "https://github.com/ultreme/golang-repo-template/releases/download/v1.0.0/golang-repo-template_1.0.0_Linux_x86_64.tar.gz"
    sha256 "f4187c3d6cfbd0561ea677aae1ce782b7aaa9885b965ba6b3fbc47b6e2b6c0a8"
  end

  def install
    bin.install "golang-repo-template"
  end
end
