# This file was generated by GoReleaser. DO NOT EDIT.
class Smsify < Formula
  desc "smsify"
  homepage "https://ultre.me/"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ultreme/smsify/releases/download/v1.0.0/smsify_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "be6f8c10826f1e5f90c2bea9b0bf1dcb26d42ff9e3e9a7d2891a9f6baf0a3dc5"
  elsif OS.linux?
    url "https://github.com/ultreme/smsify/releases/download/v1.0.0/smsify_1.0.0_Linux_x86_64.tar.gz"
    sha256 "4f885c33b52df37155705c41e451e2ee0c25e87edce3a6152435ddd03f636bb2"
  end

  def install
    bin.install "smsify"
  end
end
